// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWIq4GxJkRltIOMxxo8Akc3J_xrasqkw',
    appId: '1:203745722239:web:c81f43d8d349f3f81e244a',
    messagingSenderId: '203745722239',
    projectId: 'muslim-pocket-e8e32',
    authDomain: 'muslim-pocket-e8e32.firebaseapp.com',
    storageBucket: 'muslim-pocket-e8e32.appspot.com',
    measurementId: 'G-1LLRT1LCDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVSJZlRLK1U-2A83P5GLdXg4P59-yirQ',
    appId: '1:203745722239:android:ca943fba5437110e1e244a',
    messagingSenderId: '203745722239',
    projectId: 'muslim-pocket-e8e32',
    storageBucket: 'muslim-pocket-e8e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ENV['AUTH_TOKEN'],
    appId: '1:203745722239:ios:f827dcfe08743db01e244a',
    messagingSenderId: '203745722239',
    projectId: 'muslim-pocket-e8e32',
    storageBucket: 'muslim-pocket-e8e32.appspot.com',
    iosBundleId: 'com.muslim.pocket.muslimpocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ENV['AUTH_TOKEN'],
    appId: '1:203745722239:ios:d404d0a7dcc3f3f91e244a',
    messagingSenderId: '203745722239',
    projectId: 'muslim-pocket-e8e32',
    storageBucket: 'muslim-pocket-e8e32.appspot.com',
    iosBundleId: 'com.muslim.pocket.muslimpocket.RunnerTests',
  );
}
